'use client';

import { useState, useRef, useCallback, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { X, Save, Camera, Trash2, Move } from 'lucide-react';

// ── Types ──────────────────────────────────────────────────────────

export interface SavedCameraAngle {
  id: string;
  name: string;
  roomType: string;
  position: { x: number; y: number }; // 2D floor-plan coordinates (normalized 0-1)
  target: { x: number; y: number };
  isAutoGenerated?: boolean;
}

interface RoomFloorInfo {
  roomType: string;
  label: string;
  rect: { x: number; y: number; width: number; height: number }; // normalized 0-1
}

// ── Default floor plan layout (normalized 0-1) ────────────────────

const DEFAULT_ROOMS: RoomFloorInfo[] = [
  { roomType: 'living', label: 'Living', rect: { x: 0.02, y: 0.35, width: 0.45, height: 0.63 } },
  { roomType: 'kitchen', label: 'Kitchen', rect: { x: 0.02, y: 0.02, width: 0.45, height: 0.30 } },
  { roomType: 'mbr', label: 'M. Bedroom', rect: { x: 0.52, y: 0.35, width: 0.46, height: 0.63 } },
  { roomType: 'bed2', label: 'Bedroom 2', rect: { x: 0.52, y: 0.02, width: 0.46, height: 0.30 } },
];

// ── Auto-generated angle presets per room ─────────────────────────

const AUTO_ANGLES: Record<string, Array<{ name: string; position: { x: number; y: number }; target: { x: number; y: number } }>> = {
  living: [
    { name: 'Corner View', position: { x: 0.08, y: 0.88 }, target: { x: 0.35, y: 0.50 } },
    { name: 'Entrance View', position: { x: 0.40, y: 0.92 }, target: { x: 0.25, y: 0.55 } },
    { name: 'Window-side', position: { x: 0.30, y: 0.40 }, target: { x: 0.20, y: 0.65 } },
  ],
  mbr: [
    { name: 'Door View', position: { x: 0.58, y: 0.40 }, target: { x: 0.75, y: 0.60 } },
    { name: 'Bedside View', position: { x: 0.80, y: 0.70 }, target: { x: 0.65, y: 0.50 } },
  ],
  kitchen: [
    { name: 'Entrance View', position: { x: 0.08, y: 0.05 }, target: { x: 0.30, y: 0.18 } },
    { name: 'Counter Close-up', position: { x: 0.35, y: 0.10 }, target: { x: 0.25, y: 0.20 } },
  ],
  bed2: [
    { name: 'Door View', position: { x: 0.58, y: 0.05 }, target: { x: 0.75, y: 0.18 } },
    { name: 'Window-side', position: { x: 0.85, y: 0.12 }, target: { x: 0.70, y: 0.20 } },
    { name: 'Desk Corner', position: { x: 0.65, y: 0.25 }, target: { x: 0.55, y: 0.15 } },
  ],
};

// ── Props ──────────────────────────────────────────────────────────

interface CameraAnglePickerProps {
  roomType: string;
  savedAngles: SavedCameraAngle[];
  onSaveAngle: (angle: SavedCameraAngle) => void;
  onDeleteAngle: (id: string) => void;
  onClose: () => void;
}

// ── Component ──────────────────────────────────────────────────────

export function CameraAnglePicker({
  roomType,
  savedAngles,
  onSaveAngle,
  onDeleteAngle,
  onClose,
}: CameraAnglePickerProps) {
  const floorRef = useRef<HTMLDivElement>(null);
  const [placing, setPlacing] = useState(false);
  const [dragging, setDragging] = useState(false);
  const [cameraPos, setCameraPos] = useState<{ x: number; y: number } | null>(null);
  const [targetPos, setTargetPos] = useState<{ x: number; y: number } | null>(null);
  const [angleName, setAngleName] = useState('');
  const [dragStart, setDragStart] = useState<{ x: number; y: number } | null>(null);

  const rooms = DEFAULT_ROOMS;
  const autoAngles = AUTO_ANGLES[roomType] || [];
  const roomInfo = rooms.find((r) => r.roomType === roomType);

  // Get normalized coordinates from mouse event
  const getNormCoords = useCallback(
    (e: React.MouseEvent<HTMLDivElement>): { x: number; y: number } => {
      const rect = floorRef.current!.getBoundingClientRect();
      return {
        x: (e.clientX - rect.left) / rect.width,
        y: (e.clientY - rect.top) / rect.height,
      };
    },
    [],
  );

  // Handle click on floor plan to place camera
  const handleFloorClick = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      if (dragging) return;
      const pos = getNormCoords(e);
      setCameraPos(pos);
      setTargetPos(null);
      setPlacing(true);
      setAngleName('');
    },
    [getNormCoords, dragging],
  );

  // Handle mousedown on camera dot to start drag for direction
  const handleDotMouseDown = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      e.stopPropagation();
      setDragging(true);
      setDragStart(getNormCoords(e));
    },
    [getNormCoords],
  );

  // Handle mouse move for direction arrow
  const handleMouseMove = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      if (!dragging || !cameraPos) return;
      const pos = getNormCoords(e);
      setTargetPos(pos);
    },
    [dragging, cameraPos, getNormCoords],
  );

  // Handle mouse up to finalize direction
  const handleMouseUp = useCallback(() => {
    if (dragging && cameraPos && !targetPos) {
      // If dragged but no target yet, set a default target a bit away
      setTargetPos({ x: cameraPos.x + 0.1, y: cameraPos.y + 0.1 });
    }
    setDragging(false);
    setDragStart(null);
  }, [dragging, cameraPos, targetPos]);

  // Save angle
  const handleSave = useCallback(() => {
    if (!cameraPos || !targetPos) return;
    const name = angleName.trim() || `Custom Angle ${savedAngles.filter((a) => !a.isAutoGenerated).length + 1}`;
    const newAngle: SavedCameraAngle = {
      id: `custom-${Date.now()}`,
      name,
      roomType,
      position: cameraPos,
      target: targetPos,
      isAutoGenerated: false,
    };
    onSaveAngle(newAngle);
    setCameraPos(null);
    setTargetPos(null);
    setPlacing(false);
    setAngleName('');
  }, [cameraPos, targetPos, angleName, roomType, savedAngles, onSaveAngle]);

  // Select auto-generated angle
  const handleSelectAuto = useCallback(
    (auto: { name: string; position: { x: number; y: number }; target: { x: number; y: number } }) => {
      // Create and save auto angle if not already saved
      const alreadySaved = savedAngles.some(
        (a) => a.isAutoGenerated && a.name === auto.name && a.roomType === roomType,
      );
      if (!alreadySaved) {
        const newAngle: SavedCameraAngle = {
          id: `auto-${roomType}-${auto.name.toLowerCase().replace(/\s+/g, '-')}`,
          name: auto.name,
          roomType,
          position: auto.position,
          target: auto.target,
          isAutoGenerated: true,
        };
        onSaveAngle(newAngle);
      }
    },
    [savedAngles, roomType, onSaveAngle],
  );

  // Compute direction angle (in degrees) for rendering the arrow
  const getDirectionAngle = useCallback(() => {
    if (!cameraPos || !targetPos) return 0;
    const dx = targetPos.x - cameraPos.x;
    const dy = targetPos.y - cameraPos.y;
    return Math.atan2(-dy, dx) * (180 / Math.PI);
  }, [cameraPos, targetPos]);

  // Compute distance between camera and target
  const getDistance = useCallback(() => {
    if (!cameraPos || !targetPos) return 0;
    const dx = targetPos.x - cameraPos.x;
    const dy = targetPos.y - cameraPos.y;
    return Math.sqrt(dx * dx + dy * dy);
  }, [cameraPos, targetPos]);

  // Filter saved angles for this room
  const roomSavedAngles = savedAngles.filter((a) => a.roomType === roomType);
  const autoSaved = roomSavedAngles.filter((a) => a.isAutoGenerated);
  const customSaved = roomSavedAngles.filter((a) => !a.isAutoGenerated);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      setDragging(false);
    };
  }, []);

  const directionAngle = getDirectionAngle();
  const distance = getDistance();

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60" onClick={onClose}>
      <div
        className="bg-slate-800 border border-slate-600 rounded-xl w-full max-w-2xl mx-4 overflow-hidden shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3 border-b border-slate-700">
          <h2 className="text-sm font-semibold text-white flex items-center gap-2">
            <Camera className="w-4 h-4 text-teal-400" />
            Camera Angle Picker — {roomInfo?.label || roomType}
          </h2>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="flex flex-col md:flex-row">
          {/* Left: Floor plan */}
          <div className="flex-1 p-4">
            <div
              ref={floorRef}
              className="relative w-full aspect-square bg-slate-700 rounded-lg overflow-hidden cursor-crosshair select-none"
              onMouseDown={handleFloorClick}
              onMouseMove={handleMouseMove}
              onMouseUp={handleMouseUp}
              onMouseLeave={handleMouseUp}
            >
              {/* Grid pattern */}
              <div
                className="absolute inset-0 opacity-10"
                style={{
                  backgroundImage:
                    'linear-gradient(rgba(255,255,255,0.1) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.1) 1px, transparent 1px)',
                  backgroundSize: '10% 10%',
                }}
              />

              {/* Room rectangles */}
              {rooms.map((room) => {
                const isActive = room.roomType === roomType;
                return (
                  <div
                    key={room.roomType}
                    className={`absolute border-2 rounded-md flex items-center justify-center text-[9px] font-medium transition-colors ${
                      isActive
                        ? 'border-teal-500 bg-teal-500/20 text-teal-300'
                        : 'border-slate-500 bg-slate-600/30 text-slate-400'
                    }`}
                    style={{
                      left: `${room.rect.x * 100}%`,
                      top: `${room.rect.y * 100}%`,
                      width: `${room.rect.width * 100}%`,
                      height: `${room.rect.height * 100}%`,
                    }}
                  >
                    <span className="truncate px-1">{room.label}</span>
                  </div>
                );
              })}

              {/* Saved auto-generated angles (dots) */}
              {autoSaved
                .filter((a) => a.roomType === roomType)
                .map((angle) => (
                  <div key={angle.id} className="absolute" style={{ left: `${angle.position.x * 100}%`, top: `${angle.position.y * 100}%` }}>
                    {/* Arrow line */}
                    <svg
                      className="absolute"
                      style={{
                        left: 0,
                        top: 0,
                        width: '100%',
                        height: '100%',
                        pointerEvents: 'none',
                        overflow: 'visible',
                      }}
                    >
                      <line
                        x1="0"
                        y1="0"
                        x2={`${(angle.target.x - angle.position.x) * 100}%`}
                        y2={`${(angle.target.y - angle.position.y) * 100}%`}
                        stroke="#14b8a6"
                        strokeWidth="1.5"
                        strokeDasharray="3 2"
                        opacity={0.5}
                      />
                    </svg>
                    <div className="w-2 h-2 rounded-full bg-teal-500 -translate-x-1/2 -translate-y-1/2 shadow-sm" />
                  </div>
                ))}

              {/* Camera position dot */}
              {cameraPos && (
                <>
                  {/* Direction arrow */}
                  {targetPos && (
                    <svg
                      className="absolute inset-0 w-full h-full pointer-events-none"
                      style={{ zIndex: 10 }}
                    >
                      <defs>
                        <marker
                          id="arrowhead"
                          markerWidth="6"
                          markerHeight="4"
                          refX="6"
                          refY="2"
                          orient="auto"
                        >
                          <polygon points="0 0, 6 2, 0 4" fill="#60a5fa" />
                        </marker>
                      </defs>
                      <line
                        x1={`${cameraPos.x * 100}%`}
                        y1={`${cameraPos.y * 100}%`}
                        x2={`${targetPos.x * 100}%`}
                        y2={`${targetPos.y * 100}%`}
                        stroke="#60a5fa"
                        strokeWidth="2"
                        markerEnd="url(#arrowhead)"
                      />
                      {/* Distance label */}
                      <text
                        x={`${((cameraPos.x + targetPos.x) / 2) * 100}%`}
                        y={`${((cameraPos.y + targetPos.y) / 2) * 100 - 1.5}%`}
                        fill="#93c5fd"
                        fontSize="8"
                        textAnchor="middle"
                        style={{ fontFamily: 'monospace' }}
                      >
                        ~{(distance * 12).toFixed(1)}m
                      </text>
                    </svg>
                  )}

                  {/* Camera dot (draggable) */}
                  <div
                    className="absolute w-4 h-4 -translate-x-1/2 -translate-y-1/2 cursor-grab active:cursor-grabbing z-20"
                    style={{ left: `${cameraPos.x * 100}%`, top: `${cameraPos.y * 100}%` }}
                    onMouseDown={handleDotMouseDown}
                  >
                    <div className="w-full h-full rounded-full bg-blue-400 border-2 border-white shadow-md flex items-center justify-center">
                      <div className="w-1.5 h-1.5 rounded-full bg-white" />
                    </div>
                    <div className="absolute -bottom-4 left-1/2 -translate-x-1/2 text-[8px] text-blue-300 whitespace-nowrap flex items-center gap-0.5">
                      <Move className="w-2.5 h-2.5" />
                      Camera
                    </div>
                  </div>
                </>
              )}

              {/* Instructions overlay */}
              {!cameraPos && !dragging && (
                <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                  <div className="text-center text-slate-400">
                    <Camera className="w-6 h-6 mx-auto mb-1.5 opacity-50" />
                    <div className="text-[10px]">Click to place camera</div>
                    <div className="text-[8px] text-slate-500">Then drag to aim</div>
                  </div>
                </div>
              )}
            </div>

            {/* Camera info */}
            {cameraPos && (
              <div className="mt-3 p-2.5 bg-slate-700/50 rounded-lg text-[10px] text-slate-300 font-mono">
                <div className="flex justify-between">
                  <span>
                    Camera: Y=1.6m · ({cameraPos.x.toFixed(2)}, {cameraPos.y.toFixed(2)})
                  </span>
                  {targetPos && (
                    <span>
                      Target: 3m ahead · ({targetPos.x.toFixed(2)}, {targetPos.y.toFixed(2)})
                    </span>
                  )}
                </div>
              </div>
            )}
          </div>

          {/* Right: Controls & Saved Angles */}
          <div className="w-full md:w-56 border-t md:border-t-0 md:border-l border-slate-700 p-4 space-y-4 overflow-y-auto max-h-[400px]">
            {/* 3D thumbnail preview */}
            <div className="bg-slate-700 rounded-lg aspect-[4/3] flex items-center justify-center">
              <div className="text-center text-slate-500">
                <div className="text-lg mb-1">🏗️</div>
                <div className="text-[9px]">3D Preview</div>
                <div className="text-[8px] text-slate-600 mt-0.5">(viewport)</div>
              </div>
            </div>

            {/* Camera name + save */}
            {cameraPos && targetPos && (
              <div className="space-y-2">
                <Label className="text-[11px] text-slate-400">Angle Name</Label>
                <Input
                  value={angleName}
                  onChange={(e) => setAngleName(e.target.value)}
                  placeholder="e.g. Sofa Close-up"
                  className="h-7 text-xs bg-slate-700 border-slate-600 text-white placeholder:text-slate-500"
                />
                <Button
                  size="sm"
                  className="w-full bg-teal-600 hover:bg-teal-500 text-xs h-7"
                  onClick={handleSave}
                >
                  <Save className="w-3 h-3 mr-1" />
                  Save Custom Angle
                </Button>
              </div>
            )}

            {/* Auto-generated angles */}
            <div>
              <h3 className="text-[10px] text-slate-400 font-medium uppercase tracking-wider mb-2">
                Auto-generated
              </h3>
              <div className="space-y-1">
                {autoAngles.map((auto) => {
                  const isSaved = autoSaved.some((a) => a.name === auto.name);
                  return (
                    <button
                      key={auto.name}
                      onClick={() => handleSelectAuto(auto)}
                      className={`w-full text-left text-[11px] px-2.5 py-1.5 rounded transition flex items-center gap-1.5 ${
                        isSaved
                          ? 'bg-teal-600/20 text-teal-300 border border-teal-600/40'
                          : 'bg-slate-700/50 text-slate-400 hover:bg-slate-700 border border-transparent'
                      }`}
                    >
                      <Camera className="w-2.5 h-2.5 shrink-0" />
                      <span className="truncate">{auto.name}</span>
                      {isSaved && <span className="ml-auto text-[8px] text-teal-400">✓</span>}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Custom saved angles */}
            {customSaved.length > 0 && (
              <div>
                <h3 className="text-[10px] text-slate-400 font-medium uppercase tracking-wider mb-2">
                  Custom Angles
                </h3>
                <div className="space-y-1">
                  {customSaved.map((angle) => (
                    <div
                      key={angle.id}
                      className="flex items-center gap-1.5 bg-slate-700/50 rounded px-2.5 py-1.5"
                    >
                      <span className="text-[11px] text-slate-300 truncate flex-1">
                        {angle.name}
                      </span>
                      <button
                        onClick={() => onDeleteAngle(angle.id)}
                        className="text-slate-500 hover:text-red-400 transition-colors shrink-0"
                      >
                        <Trash2 className="w-3 h-3" />
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {autoSaved.length === 0 && customSaved.length === 0 && (
              <div className="text-center py-4">
                <div className="text-[10px] text-slate-500">
                  No angles saved yet.
                </div>
                <div className="text-[9px] text-slate-600 mt-0.5">
                  Click auto-generated angles or place your own.
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
